views:
  - name: pessoas_view
    description: Complete view of persons and companies data
    
    cubes:
      - join_path: pessoas
        includes:
          - cod_pessoa
          - nom_pessoa
          - nom_reduzido_pessoa
          - dta_cadastramento
          - tipo_pessoa
          - status_pessoa
          - ind_pessoa_empresa
          - ind_forn_homolog
          - count
          - count_pessoas_fisicas
          - count_pessoas_juridicas
          - count_ativos
          - count_inativos
          - count_filiais
          - count_fornecedores_homologados
